#!/bin/bash

printf "\n${YELLOW}Installing volta...${NC} \n"
curl "https://get.volta.sh/" | /usr/bin/bash

~/.volta/bin/volta install node
~/.volta/bin/volta install yarn@1
~/.volta/bin/volta install pnpm
printf "\n${YELLOW}Volta installation completed ✅${NC} \n"