#!/bin/bash
printf "\n${YELLOW}Installing ZSH...${NC} \n"
sudo apt install -y zsh-autosuggestions zsh-syntax-highlighting zsh
sh -c"CHSH=yes RUNZSH=no KEEP_ZSHRC=no $(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
printf "\n${YELLOW}Zsh instalattion completed ✅${NC} \n"

printf "\n${YELLOW}Installing ZSH plugins...${NC} \n"
/usr/bin/zsh -c "git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
/usr/bin/zsh -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
/usr/bin/zsh -c "git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting"

# Path to the .zshrc file
zshrc_file=~/.zshrc

# Line to find and replace
old_line="plugins=(git)"
new_line="plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting)"

sed -i "s/$old_line/$new_line/g" "$zshrc_file"

echo "neofetch" >> ~/.zshenv
echo "export VOLTA_HOME=\"$HOME/.volta\"" >> ~/.zshrc
echo "export PATH=\"$VOLTA_HOME/bin:$PATH\"" >> ~/.zshrc
printf "\n${YELLOW}ZSH plugins and configuration completed ✅${NC} \n"