#!/bin/bash

sudo apt install zsh-autosuggestions zsh-syntax-highlighting zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

# Path to the .zshrc file
zshrc_file=~/.zshrc

# Line to find and replace
old_line="plugins=(git)"
new_line="plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting)"

# Check if .zshrc file exists
if [ -f "$zshrc_file" ]; then
    # Use sed to find and replace the line
    sed -i "s/$old_line/$new_line/g" "$zshrc_file"
    echo "Replacement done successfully."
else
    echo "Error: ~/.zshrc file not found."
fi